apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-jicofo
  labels:
    app.kubernetes.io/name: jitsi-jicofo
    app.kubernetes.io/component: focus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jitsi-jicofo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jitsi-jicofo
        app.kubernetes.io/component: focus
        ofc/network-jitsi: "true"
    spec:
      containers:
        - name: jicofo
          image: jitsi/jicofo:stable
          envFrom:
            - secretRef:
                name: jitsi-secret
