apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-web.yaml
  - deployment-prosody.yaml
  - deployment-jicofo.yaml
  - deployment-jvb.yaml
  - service-web.yaml
  - service-prosody.yaml
  - service-jvb.yaml
  - ingress.yaml
