apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - matrix.DOMAIN_PLACEHOLDER
      secretName: synapse-tls
  rules:
    - host: matrix.DOMAIN_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse
                port:
                  number: 8008
