apiVersion: v1
kind: Service
metadata:
  name: synapse
  labels:
    app.kubernetes.io/name: synapse
spec:
  selector:
    app.kubernetes.io/name: synapse
  ports:
    - port: 8008
      targetPort: 8008
