apiVersion: v1
kind: Service
metadata:
  name: element
  labels:
    app.kubernetes.io/name: element
spec:
  selector:
    app.kubernetes.io/name: element
  ports:
    - port: 80
      targetPort: 80
